// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function DeleteAPIKey(arg1) {
  return window['go']['main']['App']['DeleteAPIKey'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function EndSession(arg1) {
  return window['go']['main']['App']['EndSession'](arg1);
}

export function EnterOverlayMode() {
  return window['go']['main']['App']['EnterOverlayMode']();
}

export function ExitOverlayMode() {
  return window['go']['main']['App']['ExitOverlayMode']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetAuthStatus() {
  return window['go']['main']['App']['GetAuthStatus']();
}

export function GetDebrief(arg1) {
  return window['go']['main']['App']['GetDebrief'](arg1);
}

export function GetHotkeyStatus() {
  return window['go']['main']['App']['GetHotkeyStatus']();
}

export function GetLatestScreenshot() {
  return window['go']['main']['App']['GetLatestScreenshot']();
}

export function GetPreferences() {
  return window['go']['main']['App']['GetPreferences']();
}

export function GetSessionTranscript(arg1) {
  return window['go']['main']['App']['GetSessionTranscript'](arg1);
}

export function ListAvailableModels() {
  return window['go']['main']['App']['ListAvailableModels']();
}

export function ListCompanies() {
  return window['go']['main']['App']['ListCompanies']();
}

export function ListCompanyProblems(arg1) {
  return window['go']['main']['App']['ListCompanyProblems'](arg1);
}

export function ListDisplays() {
  return window['go']['main']['App']['ListDisplays']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function ListVoices() {
  return window['go']['main']['App']['ListVoices']();
}

export function MinimiseWindow() {
  return window['go']['main']['App']['MinimiseWindow']();
}

export function OpenInputMonitoringSettings() {
  return window['go']['main']['App']['OpenInputMonitoringSettings']();
}

export function OpenReleasePage(arg1) {
  return window['go']['main']['App']['OpenReleasePage'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function PreviewVoice(arg1) {
  return window['go']['main']['App']['PreviewVoice'](arg1);
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function SetAPIKey(arg1, arg2) {
  return window['go']['main']['App']['SetAPIKey'](arg1, arg2);
}

export function SetCaptureRegion(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SetCaptureRegion'](arg1, arg2, arg3, arg4, arg5);
}

export function SetOverlayExpanded(arg1) {
  return window['go']['main']['App']['SetOverlayExpanded'](arg1);
}

export function SnapshotDisplay(arg1) {
  return window['go']['main']['App']['SnapshotDisplay'](arg1);
}

export function StartCapture(arg1) {
  return window['go']['main']['App']['StartCapture'](arg1);
}

export function StartCompanySession(arg1, arg2) {
  return window['go']['main']['App']['StartCompanySession'](arg1, arg2);
}

export function StartMockInterview(arg1) {
  return window['go']['main']['App']['StartMockInterview'](arg1);
}

export function StartSession(arg1) {
  return window['go']['main']['App']['StartSession'](arg1);
}

export function StopCapture() {
  return window['go']['main']['App']['StopCapture']();
}

export function SynthesizeSpeech(arg1) {
  return window['go']['main']['App']['SynthesizeSpeech'](arg1);
}

export function ToggleMaximiseWindow() {
  return window['go']['main']['App']['ToggleMaximiseWindow']();
}

export function TranscribeAudio(arg1, arg2) {
  return window['go']['main']['App']['TranscribeAudio'](arg1, arg2);
}

export function UpdatePreferences(arg1) {
  return window['go']['main']['App']['UpdatePreferences'](arg1);
}
