// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {hotkey} from '../models';
import {capture} from '../models';

export function ActivateTestAccount(arg1:string,arg2:string):Promise<models.AuthStatus>;

export function CheckForUpdate():Promise<models.UpdateInfo>;

export function ClearAllLocalData():Promise<void>;

export function DeleteAPIKey(arg1:string):Promise<void>;

export function DeleteSession(arg1:string):Promise<void>;

export function EndSession(arg1:string):Promise<void>;

export function EnterOverlayMode():Promise<void>;

export function ExitOverlayMode():Promise<void>;

export function GetAppVersion():Promise<string>;

export function GetAuthStatus():Promise<models.AuthStatus>;

export function GetDebrief(arg1:string):Promise<models.Debrief>;

export function GetHotkeyStatus():Promise<hotkey.Status>;

export function GetLatestScreenshot():Promise<string>;

export function GetPreferences():Promise<models.Preferences>;

export function GetSessionTranscript(arg1:string):Promise<Array<models.Message>>;

export function ListAvailableModels():Promise<Array<models.Model>>;

export function ListCompanies():Promise<Array<models.CompanyInfo>>;

export function ListCompanyProblems(arg1:string):Promise<Array<models.Problem>>;

export function ListDisplays():Promise<Array<capture.DisplayInfo>>;

export function ListSessions():Promise<Array<models.SessionSummary>>;

export function ListStarredCompanies():Promise<Array<string>>;

export function ListVoices():Promise<Array<models.Voice>>;

export function MinimiseWindow():Promise<void>;

export function OpenInputMonitoringSettings():Promise<void>;

export function OpenReleasePage(arg1:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function PreviewVoice(arg1:string):Promise<string>;

export function QuitApp():Promise<void>;

export function RequestTestCode(arg1:string,arg2:string):Promise<void>;

export function RevealDatabaseFile():Promise<void>;

export function SendMessage(arg1:string):Promise<string>;

export function SetAPIKey(arg1:string,arg2:string):Promise<void>;

export function SetCaptureRegion(arg1:number,arg2:number,arg3:number,arg4:number,arg5:number):Promise<void>;

export function SetCompanyStarred(arg1:string,arg2:boolean):Promise<void>;

export function SetOverlayExpanded(arg1:boolean):Promise<void>;

export function SignOutTestAccount():Promise<models.AuthStatus>;

export function SnapshotDisplay(arg1:number):Promise<string>;

export function StartCapture(arg1:number):Promise<void>;

export function StartCompanySession(arg1:string,arg2:models.Problem):Promise<models.CompanySessionStart>;

export function StartMockInterview(arg1:string):Promise<models.CompanySessionStart>;

export function StartSession(arg1:string):Promise<models.Session>;

export function StopCapture():Promise<void>;

export function SynthesizeSpeech(arg1:string):Promise<string>;

export function ToggleMaximiseWindow():Promise<void>;

export function TranscribeAudio(arg1:string,arg2:string):Promise<string>;

export function UpdatePreferences(arg1:models.Preferences):Promise<void>;
