// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {capture} from '../models';

export function EndSession(arg1:string):Promise<void>;

export function EnterOverlayMode():Promise<void>;

export function ExitOverlayMode():Promise<void>;

export function GetAuthStatus():Promise<models.AuthStatus>;

export function GetLatestScreenshot():Promise<string>;

export function GetPreferences():Promise<models.Preferences>;

export function GetSessionTranscript(arg1:string):Promise<Array<models.Message>>;

export function ListAvailableModels():Promise<Array<models.Model>>;

export function ListDisplays():Promise<Array<capture.DisplayInfo>>;

export function ListSessions():Promise<Array<models.SessionSummary>>;

export function ListVoices():Promise<Array<models.Voice>>;

export function SendMessage(arg1:string):Promise<string>;

export function SetAPIKey(arg1:string,arg2:string):Promise<void>;

export function SetCaptureRegion(arg1:number,arg2:number,arg3:number,arg4:number,arg5:number):Promise<void>;

export function SetOverlayExpanded(arg1:boolean):Promise<void>;

export function SnapshotDisplay(arg1:number):Promise<string>;

export function StartCapture(arg1:number):Promise<void>;

export function StartSession(arg1:string):Promise<models.Session>;

export function StopCapture():Promise<void>;

export function SynthesizeSpeech(arg1:string):Promise<string>;

export function TranscribeAudio(arg1:string,arg2:string):Promise<string>;

export function UpdatePreferences(arg1:models.Preferences):Promise<void>;
